### ISSUE TITLE
Question: RelationRows

### ISSUE THREAD

**Issue by thebruuu** [sqlparser/python_data_lineage#4]
1st of all Congrat for you product. I really like it!

2nd A Question : why there is a cell RelationRows appearing in each table?

3rd. Question: In CSV output, when there is a TO_CHAR (or other transformation) is there a way to have the full formula ?

Thank You

**Comment by liaowuhen2** [comment]
_2nd A Question : why there is a cell RelationRows appearing in each table?_
Answer: https://docs.gudusoft.com/2.-concepts/data-lineage/indirect-dataflow

_3rd. Question: In CSV output, when there is a TO_CHAR (or other transformation) is there a way to have the full formula ?_
Answer: The full transformation is visible in the JSON return and not in the CSV return

Thank You
